### ISSUE TITLE
Youtube Downloads are currently broken

### ISSUE THREAD

**Issue by FandrewDavid** [wukko/cobalt#188]
Downloading a Video or Audio from Youtube results in a corrupted file that is 0 B worth of data and unplayable by media players
![image](https://github.com/wukko/cobalt/assets/51008604/1d2299a6-14b0-4350-8747-b948ddfe805c)
![image](https://github.com/wukko/cobalt/assets/51008604/97eeaff4-5c06-4f15-9108-281bd9769ce0)

**Comment by pixlxip** [comment]
I also have this issue. My friend, too. Here's a video:
[Screencast from 2023-08-21 21-32-26.webm](https://github.com/wukko/cobalt/assets/99521063/e32f37bc-7fea-4912-b532-40ae7bd7e93b)

**Comment by NathanBarnes117** [comment]
Yeah same here, of this issues. I’ve tried to download from YouTube to KineMaster, and it won’t work.

**Comment by wukko** [comment]
i was asleep when this happened, give me a few minutes

**Comment by wukko** [comment]
the issue is now fixed, go try it: https://co.wukko.me/ :)

**Comment by FandrewDavid** [comment]
The issue is back!
![image](https://github.com/wukko/cobalt/assets/51008604/4001e399-3039-4031-831d-2b3ddd32cb1d)

**Comment by wukko** [comment]
the issue will be fixed soon, youtube is actively blocking main cobalt instances

**Comment by FandrewDavid** [comment]
Also likely unrelated but my OS wouldn’t let me delete the .opus file after downloading it for some reason and restarting it made it stop booting  😭

**Comment by wukko** [comment]
the downloading issue has been fixed, and here's how you can fix explorer lags for opus/ogg files:

1. restart your computer and try again. sometimes it actually helps.
2. follow steps listed here: https://answers.microsoft.com/en-us/windows/forum/all/painfully-slow-file-operations-on-ogg-and-opus/2258df33-7380-43aa-bd5c-2c8053c02ecf and try deleting the file again.
3. if previous solutions didn’t help, try uninstalling “web media extensions” app in settings > programs (it may be listed differently in your system’s language) and try again.

**Comment by FandrewDavid** [comment]
It’s the actual OS that won’t actually boot not any actual media players 🥲 It just kind of indefinitely tries to load now after starting. But thank you for attempting to provide solutions and help anyway! I kinda doubt that these two are related anyway, I’m planning to just take it to a repair center tomorrow to see if I could figure out the issue.
