### ISSUE TITLE
YouTube Music songs won't download.

### ISSUE THREAD

**Issue by afq4** [wukko/cobalt#337]
It worked just fine a few days ago now I can't download anything that is from YouTube Music, and no, they are not age restricted or region locked. Try it yourself.
https://www.youtube.com/watch?v=oDLU3e34G1o
![image](https://github.com/wukko/cobalt/assets/99206769/42016e23-17aa-4ede-8380-13e24725ded5)

**Comment by princessmortix** [comment]
![image](https://github.com/wukko/cobalt/assets/47502554/520b3d27-56d8-4653-a998-9ed665d09120)
 It could be region locked, or the main instance is banned again

**Comment by princessmortix** [comment]
Actually, Youtube Music doesn't allow VPNs to see music there, you might need [another instance from this list](https://instances.hyper.lol).

As said by one of cobalt devs in their Discord:
> yes, the main instance ips are seen as vpn/being in an “unknown” country
> and thus yt music uploads are unavailable

From twitter:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">youtube is seemingly blocking vpns from accessing anything youtube music related (even with a premium account)<br><br>you don&#39;t get a proper explanation, just &quot;this video is not available&quot; if you open the page via main youtube web app<br><br>interesting part is missing country next to logo.. <a href="https://t.co/q9ZOue5EPn">pic.twitter.com/q9ZOue5EPn</a></p>&mdash; wukko (@uwukko) <a href="https://twitter.com/uwukko/status/1750941852088373388?ref_src=twsrc%5Etfw">January 26, 2024</a>

[original tweet](https://twitter.com/uwukko/status/1750941852088373388)
</blockquote>

**Comment by afq4** [comment]
> Actually, Youtube Music doesn't allow VPNs to see music there, you might need [another instance from this list](https://instances.hyper.lol).
> 
> As said by one of cobalt devs in their Discord:
> 
> > yes, the main instance ips are seen as vpn/being in an “unknown” country
> > and thus yt music uploads are unavailable
> 
> From twitter:
> 
> > youtube is seemingly blocking vpns from accessing anything youtube music related (even with a premium account)you don't get a proper explanation, just "this video is not available" if you open the page via main youtube web appinteresting part is missing country next to logo.. [pic.twitter.com/q9ZOue5EPn](https://t.co/q9ZOue5EPn)— wukko (@uwukko) [January 26, 2024](https://twitter.com/uwukko/status/1750941852088373388?ref_src=twsrc%5Etfw)
> > [original tweet](https://twitter.com/uwukko/status/1750941852088373388)

Thanks, I picked one from the instance list and now I can download again.

**Comment by wukko** [comment]
fixed, go try it: https://cobalt.tools

**Comment by Nekothegamer** [comment]
it's not fixed it still gives an error while downloading from youtube music (from the main instance)
